---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reqbin
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: reqbin
  template:
    metadata:
      labels:
        app: reqbin
    spec:
      containers:
        - name: reqbin
          image: nasa9084/reqbin
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reqbin
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reqbin
  type: NodePort
